<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="css/style.css">
</head>
<body>
<?php
require 'templates/layout/header.phtml';

if($error) : ?>
    <h2><?=$error?></h2>
<?php endif ?>

<h1>Registrarse:</h1>
<form action="<?= $base?>signUp" method="post">
    Email: <input type="email" name="email" id="email" required>
    Contraseña: <input type="password" name="contrasenia" id="contrasenia" required>
    <button type="submit">Registrar</button>
</form>
</body>
</html>