<h3>Añadir Piloto:</h3>
<form action="agregarPiloto" method="post">
Nombre:<input required type="text" name="nombre" id="">
DNI:<input required type="text" name="dni" id="">
Fecha de nacimiento:<input required type="date" name="fecha_nac" id="">
Gmail: <input required type="text" name="gmail" id="">
Dirección: <input required type="text" name="direccion" id="">
Telefono: <input required type="number" name="telefono" id="">
Número de Licencia: <input required type="number" name="licencia" id="">
<button type="submit">Enviar</button>
</form>