<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Vuelo Completo</title>
    <link rel="stylesheet" href="css/style.css">
</head>
<body>
    <?php require 'templates/layout/header.phtml'; ?>
    <table>
        <tr>
            <td>Piloto</td>
            <td>Origen</td>
            <td>Destino</td>
            <td>Cantidad de Pasajeros</td>
            <td>Duración (horas)</td>
        </tr>

        <tr><td><?= $piloto->nombre ?></td>
        <td><?= $vuelo->origen ?></td> 
        <td><?= $vuelo->destino ?></td> 
        <td><?= $vuelo->cant_pasajeros ?></td> 
        <td><?= $vuelo->duracion_vuelo ?></td>
        <td><a href="<?= $base ?>editarVuelo/<?= $vuelo->id_vuelos?>">Editar<a></td>
        <td><a href="<?= $base ?>eliminarVuelo/<?= $vuelo->id_vuelos?>" type="button">Borrar</a></td> 
        </tr>
    </table>
</body>
</html>
