<?php require 'templates/layout/header.phtml'; ?>
    <table>
        <tr>
            <td style="font-size: 30px; color: red;">Piloto</td>
            <td style="font-size: 30px; color: red;">Origen</td>
            <td style="font-size: 30px; color: red;">Destino</td>
            <td style="font-size: 30px; color: red;">Cantidad de Pasajeros</td>
            <td style="font-size: 30px; color: red;">Duración (horas)</td>
        </tr>

<?php foreach ($vuelos as $vuelo): ?>
    <tr><td style="font-size:20px"><?= $piloto->nombre ?></td>
    <td style="font-size:20px"><?= $vuelo->origen ?></td> 
    <td style="font-size:20px"><?= $vuelo->destino ?></td> 
    <td style="font-size:20px"><?= $vuelo->cant_pasajeros ?></td> 
    <td style="font-size:20px"><?= $vuelo->duracion_vuelo ?></td>
    <td><a style="font-size:20px" href="<?= $base ?>editarVuelo/<?= $vuelo->id_vuelos?>">Editar<a></td>
    <td><a style="font-size:20px" href="<?= $base ?>eliminarVuelo/<?= $vuelo->id_vuelos?>" type="button">Borrar</a></td> 
    </tr>
<?php endforeach ?>
</table>